### ISSUE TITLE
Inconsistent type in documentation

### ISSUE THREAD

**Issue by Rudloff** [KageNoNeko/osm#2]
Hello,

runQuery() does not return the same type in the abstract class and in the implementation:
https://github.com/KageNoNeko/osm/blob/90a06fc05ab28887e49e5fe1eb357552c634fd35/src/ConnectionInterface.php#L29
https://github.com/KageNoNeko/osm/blob/90a06fc05ab28887e49e5fe1eb357552c634fd35/src/OverpassConnection.php#L158

This makes my static analysis tool complain.

**Comment by KageNoNeko** [comment]
Yeah, it should be 'mixed' not 'array' in interface. It wouldn't be the same due to different possible connections
